OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "<your api key>"
  proxy: "<your proxy>"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "<the book>"
  file_format: "pdf"
  to_lan: "Chinese"
  style: "plain"
  rest_port: 5003